export enum ROUTER_ENUM {
  REGISTRATION = '/registration',
  LOGIN = '/login',
  ACTIVATE = '/activate',
  USER = '/user',
  WALLETS = '/wallets',
  WALLET = '/wallet',
  OPERATIONS = '/operations',
  CATEGORIES = '/categories',
  BASIC_CATEGORIES = '/basiccategories',
  STATISTICS = '/statistics',
  // DYNAMIC
  LINK = ':/link',
  TYPE = '/:type',
  WALLET_ID = '/:walletId',
  USER_ID = '/:userId',
  OPERATION_ID = '/:operationId',
  CATEGORY_ID = '/:categoryId',
  START_DATE = '/:startDate',
  FINISH_DATE = '/:finishDate',
}
