export enum RouterEnum {
  ClientUrl = 'http://localhost:4200',
  ApiUrl = 'http://localhost:5000',
  Base = '/api/groshy',
  Registration = '/registration',
  Login = '/login',
  Logout = '/logout',
  Activate = '/activate',
  Refresh = '/refresh',
  User = '/user',
  Wallets = '/wallets',
  Expense = '/expense',
  ExpenseStatistics = '/expense/statistics',
  FirstExpense = '/expense-first',
  Income = '/income',
  IncomeStatistics = '/income/statistics',
  FirstIncome = '/income-first',
  Categories = '/categories',
}
